### ISSUE TITLE
Alias missing `exec_compatible_with`, `exec_properties`, and `toolchains` attributes in latest rolling

### ISSUE THREAD

**Issue by cpsauer** [fmeum/with_cfg.bzl#15]
Hey, @fmeum! Hope you're doing well :)

I just got back from a trip and started updating our team to the latest bazel rolling (7.0.0-pre.20230917.3). It unfortunately breaks with_cfg.bzl; figured you'd want a heads up. There are no longer `exec_compatible_with`, `exec_properties`, nor `toolchains` attributes on aliases, it seems, including the one inside with_cfg, leading to errors like
```
ERROR: no such attribute 'exec_compatible_with' in 'alias' rule
ERROR: no such attribute 'exec_properties' in 'alias' rule
ERROR: no such attribute 'toolchains' in 'alias' rule
```

Any thoughts on the best way to fix? Any chance I could ask for your help?

It does work on the prior bazel rolling, 7.0.0-pre.20230917.3. Quick searches of Bazel weren't bringing up issues/commits describing the intent to make these changes, so maybe it's a mistake by them? I figured I should write you, since you probably already have more of the puzzle pieces in your head. 

-Chris
P.S. I smiled at the clever name change to simplify the load statement :)

**Comment by fmeum** [comment]
Thanks for the heads-up, I found the breaking change and submitted a fix.

> P.S. I smiled at the clever name change to simplify the load statement :)

I also smiled when I noticed that this was possible :-)

**Comment by fmeum** [comment]
@cpsauer Btw, I will give [a talk about this project](https://rsvp.withgoogle.com/events/bazelcon2023/sessions/day1-talk14) at this year's BazelCon. If you have something like a favorite use case you could share, I could incorporate it in the talk.

**Comment by cpsauer** [comment]
:) Sure! We have two categories of use cases that might be interesting:
1) Flagless builds, like we'd talked about in that other issue. This is similar--but a little different in user motivation--than the rule-generation one you talk about in the talk description. I think most people may *first* be motivated use these as one-offs, to solve the problem of having flags/configuration that always needs to be supplied with a given target but that people keep forgetting--or to enable multiple differently configured targets to be built at the same time. I think people will then often subsequently discover that it's worth reusing them.
2) Making configuration easy in macros. As an example, we have one where we set the platform to android when rolling up maven dependencies in our (often requested but still not open sourced 🤦🏻‍♂️) distributable AAR rule.
