### ISSUE TITLE
Support dash in setting names

### ISSUE THREAD

**Issue by Swey9** [fmeum/with_cfg.bzl#60]
Since the flags augmented by the transitions are converted to attributes, and dash characters (`-`) aren't supported in attributes, it is impossible to use with_cfg on settings which are located in a path that contains a dash.

This should probably be supported somehow.

**Comment by fmeum** [comment]
As far as I can tell:

* `Label(//my/config-pkg:setting)` should work
* `Label(//my/pkg:config-setting)` currently doesn't work due to what you described.

Is that what you are seeing?

**Comment by Swey9** [comment]
Oh that's true, that was what I experienced, thought it would act the same with directory names.
Thought about the following fix, but this could cause conflicts in case of another setting with the same name but with underscores, is it a conflict we're willing to take?
And of course, I'll send a fix once I figure out how to manage this conflict

**Comment by fmeum** [comment]
> Thought about the following fix, but this could cause conflicts in case of another setting with the same name but with underscores, is it a conflict we're willing to take?

That shouldn't be an issue. The line I linked prepends the attribute name with a hash of the full label, which should avoid collisions.
