### ISSUE TITLE
Handle shared library dependencies of `cc_binary`

### ISSUE THREAD

**Issue by fmeum** [fmeum/with_cfg.bzl#85]
The RPATHs of a `cc_binary` are determined at link time and may encode relative paths to the associated runfiles directory. Since the symlinked executable created by the transition wrapper has a different name, it will fail to find those libraries.

Instead of symlinking in the transition wrapper, `with_cfg.bzl` whould emit a wrapper script that `execv`'s the target.

**Comment by fmeum** [comment]
After more consideration, this should not be a problem as `with_cfg.bzl` ensures that the original target and the transitioned target both have the same basename. Only the basename shows up in RPATHs.

**Comment by keith** [comment]
i think the path shows up too? in some cases the runpath is `$ORIGIN/../../../foo.so`?

**Comment by fmeum** [comment]
Good catch, I forgot about that situation. I think I have an idea, I just need to come up with a good test setup first to confirm it.
